### ISSUE TITLE
ENH: Create fbo.gov solicitation scanner

### ISSUE THREAD

**Issue by csmcallister** [GSA/tbm-scan#1]
## Acceptance Criteria
Given that solicitations are posted to fbo.gov, when a CO posts a TBM solicitation, there should be a scanner that captures that solicitation in a machine-readable format.
  
## Tasks
- [x] Adapt [srt-fbo-scraper](https://github.com/GSA/srt-fbo-scraper) to scan all solicitations between a given date range. When a date range isn't specified, scan the most recent FTP dump.
- [x] Determine which solicitation types (e.g. Pre-solicitation, Modifications, etc.) should be captured or if all are applicable.
- [x] Create a GitHub repo for project and source code there.
- [x] Determine a heuristic for determining whether or not a solicitation is TBM-related.
- [x] Incorporate heuristic to identify TBM solicitations into the FBO scanner.

**Comment by csmcallister** [comment]
closed by 26904fb after a run on 7/18/19 found a TBM solicitation from 7/16/19.
